#include <dawn/webgpu.h>

WGPUDeviceDescriptor z_WGPU_DEVICE_DESCRIPTOR_INIT() {
  return WGPU_DEVICE_DESCRIPTOR_INIT;
}
WGPURequestAdapterOptions z_WGPU_REQUEST_ADAPTER_OPTIONS_INIT() {
  return WGPU_REQUEST_ADAPTER_OPTIONS_INIT;
}
WGPULimits z_WGPU_LIMITS_INIT() { return WGPU_LIMITS_INIT; }
WGPUCommandEncoderDescriptor z_WGPU_COMMAND_ENCODER_DESCRIPTOR_INIT() {
  return WGPU_COMMAND_ENCODER_DESCRIPTOR_INIT;
}
WGPUCommandBufferDescriptor z_WGPU_COMMAND_BUFFER_DESCRIPTOR_INIT() {
  return WGPU_COMMAND_BUFFER_DESCRIPTOR_INIT;
}
WGPUSurfaceConfiguration z_WGPU_SURFACE_CONFIGURATION_INIT() {
  return WGPU_SURFACE_CONFIGURATION_INIT;
}
WGPUSurfaceCapabilities z_WGPU_SURFACE_CAPABILITIES_INIT() {
  return WGPU_SURFACE_CAPABILITIES_INIT;
}
WGPUSurfaceTexture z_WGPU_SURFACE_TEXTURE_INIT() {
  return WGPU_SURFACE_TEXTURE_INIT;
}
WGPUTextureViewDescriptor z_WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT() {
  return WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
}
WGPURenderPassDescriptor z_WGPU_RENDER_PASS_DESCRIPTOR_INIT() {
  return WGPU_RENDER_PASS_DESCRIPTOR_INIT;
}
WGPURenderPassColorAttachment z_WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT() {
  return WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT;
}
