#include <dawn/webgpu.h>

WGPUDeviceDescriptor z_WGPU_DEVICE_DESCRIPTOR_INIT() {
  return WGPU_DEVICE_DESCRIPTOR_INIT;
}
WGPURequestAdapterOptions z_WGPU_REQUEST_ADAPTER_OPTIONS_INIT() {
  return WGPU_REQUEST_ADAPTER_OPTIONS_INIT;
}
WGPULimits z_WGPU_LIMITS_INIT() { return WGPU_LIMITS_INIT; }
WGPUCommandEncoderDescriptor z_WGPU_COMMAND_ENCODER_DESCRIPTOR_INIT() {
  return WGPU_COMMAND_ENCODER_DESCRIPTOR_INIT;
}
WGPUCommandBufferDescriptor z_WGPU_COMMAND_BUFFER_DESCRIPTOR_INIT() {
  return WGPU_COMMAND_BUFFER_DESCRIPTOR_INIT;
}
WGPUSurfaceConfiguration z_WGPU_SURFACE_CONFIGURATION_INIT() {
  return WGPU_SURFACE_CONFIGURATION_INIT;
}
WGPUSurfaceCapabilities z_WGPU_SURFACE_CAPABILITIES_INIT() {
  return WGPU_SURFACE_CAPABILITIES_INIT;
}
WGPUSurfaceTexture z_WGPU_SURFACE_TEXTURE_INIT() {
  return WGPU_SURFACE_TEXTURE_INIT;
}
WGPUTextureViewDescriptor z_WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT() {
  return WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
}
WGPURenderPassDescriptor z_WGPU_RENDER_PASS_DESCRIPTOR_INIT() {
  return WGPU_RENDER_PASS_DESCRIPTOR_INIT;
}
WGPURenderPassColorAttachment z_WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT() {
  return WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT;
}
WGPUShaderModuleDescriptor z_WGPU_SHADER_MODULE_DESCRIPTOR_INIT() {
  return WGPU_SHADER_MODULE_DESCRIPTOR_INIT;
}
WGPUShaderSourceWGSL z_WGPU_SHADER_SOURCE_WGSL_INIT() {
  return WGPU_SHADER_SOURCE_WGSL_INIT;
}
WGPUBufferDescriptor z_WGPU_BUFFER_DESCRIPTOR_INIT() {
  return WGPU_BUFFER_DESCRIPTOR_INIT;
}
WGPURenderPipelineDescriptor z_WGPU_RENDER_PIPELINE_DESCRIPTOR_INIT() {
  return WGPU_RENDER_PIPELINE_DESCRIPTOR_INIT;
}
WGPUVertexState z_WGPU_VERTEX_STATE_INIT() {
  return WGPU_VERTEX_STATE_INIT;
}
WGPUFragmentState z_WGPU_FRAGMENT_STATE_INIT() {
  return WGPU_FRAGMENT_STATE_INIT;
}
WGPUPrimitiveState z_WGPU_PRIMITIVE_STATE_INIT() {
  return WGPU_PRIMITIVE_STATE_INIT;
}
WGPUDepthStencilState z_WGPU_DEPTH_STENCIL_STATE_INIT() {
  return WGPU_DEPTH_STENCIL_STATE_INIT;
}
WGPUMultisampleState z_WGPU_MULTISAMPLE_STATE_INIT() {
  return WGPU_MULTISAMPLE_STATE_INIT;
}
WGPUColorTargetState z_WGPU_COLOR_TARGET_STATE_INIT() {
  return WGPU_COLOR_TARGET_STATE_INIT;
}
WGPUVertexBufferLayout z_WGPU_VERTEX_BUFFER_LAYOUT_INIT() {
  return WGPU_VERTEX_BUFFER_LAYOUT_INIT;
}
WGPUVertexAttribute z_WGPU_VERTEX_ATTRIBUTE_INIT() {
  return WGPU_VERTEX_ATTRIBUTE_INIT;
}
WGPUBindGroupLayoutEntry z_WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT() {
  return WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT;
}
WGPUBindGroupLayoutDescriptor z_WGPU_BIND_GROUP_LAYOUT_DESCRIPTOR_INIT() {
  return WGPU_BIND_GROUP_LAYOUT_DESCRIPTOR_INIT;
}
WGPUPipelineLayoutDescriptor z_WGPU_PIPELINE_LAYOUT_DESCRIPTOR_INIT() {
  return WGPU_PIPELINE_LAYOUT_DESCRIPTOR_INIT;
}
WGPUBlendState z_WGPU_BLEND_STATE_INIT() {
  return WGPU_BLEND_STATE_INIT;
}
WGPUBlendComponent z_WGPU_BLEND_COMPONENT_INIT() {
  return WGPU_BLEND_COMPONENT_INIT;
}
WGPUBufferBindingLayout z_WGPU_BUFFER_BINDING_LAYOUT_INIT() {
  return WGPU_BUFFER_BINDING_LAYOUT_INIT;
}
WGPUSamplerBindingLayout z_WGPU_SAMPLER_BINDING_LAYOUT_INIT() {
  return WGPU_SAMPLER_BINDING_LAYOUT_INIT;
}
WGPUTextureBindingLayout z_WGPU_TEXTURE_BINDING_LAYOUT_INIT() {
  return WGPU_TEXTURE_BINDING_LAYOUT_INIT;
}
WGPUStorageTextureBindingLayout z_WGPU_STORAGE_TEXTURE_BINDING_LAYOUT_INIT() {
  return WGPU_STORAGE_TEXTURE_BINDING_LAYOUT_INIT;
}
WGPUStencilFaceState z_WGPU_STENCIL_FACE_STATE_INIT() {
  return WGPU_STENCIL_FACE_STATE_INIT;
}
WGPUBindGroupDescriptor z_WGPU_BIND_GROUP_DESCRIPTOR_INIT() {
  return WGPU_BIND_GROUP_DESCRIPTOR_INIT;
}
WGPUBindGroupEntry z_WGPU_BIND_GROUP_ENTRY_INIT() {
  return WGPU_BIND_GROUP_ENTRY_INIT;
}
